
["Fishing Dangers Config"]
	#Danger spawn chance, default:0.1
	"Danger spawn chance" = 0.1
	#Dangers list. Example: ["minecraft:tnt","minecraft:drowned","minecraft:fireball","minecraft:anvil","minecraft:player", "minecraft:lightning"]
	"Dangers List" = ["minecraft:tnt", "artifacts:mimic", "specialmobs:drowned", "specialmobs:skeleton", "minecraft:guardian", "alexsmobs:crocodile"]
	#Chance of each entity in Dangers list, match with Dangers list order 
	#First number will be the spawn chance of the first entity in danger list 
	#Total chance should be between 0 and 1. 
	#Example: [0.5,0.3,0.15,0.05]
	"Chance List" = [0.2, 0.2, 0.2, 0.2, 0.15, 0.05]

