
[general]
	#Show empty armor icons?
	"Show empty icons" = false
	#Colors must be specified in #RRGGBB format
	"color values" = ["#734e41", "#FFFFFF", "#40ffec", "#363232", "#ff2727", "#d747ff", "#3dff4a", "#ffd727", "#4436ff", "#ff8b26", "#000000"]
	#Always show armor bar even if empty?
	"Always show bar" = false

