
["Droprates: (0 is never drop, 20 is always drop)"]
	#DEFAULT = 1
	"Archaic Heart Droprate" = 0
	#DEFAULT = 3
	"Beating Heart Droprate" = 0
	#DEFAULT = 8
	"Sweet Heart Droprate" = 0

["Enabled/Disabled Spells: (All are set to true by default)"]
	"Self Propulsion Enabled" = false
	"Force of Wind Enabled" = false
	"Strike From Above Enabled" = false
	"Everchanging Skies Enabled" = false
	"Dying Knowledge Enabled" = false
	"Linguist Enabled" = false
	"Airy Protection Enabled" = false
	"Lifebringer Enabled" = false
	"Beast Tamer Enabled" = false
	"Wild Aid Enabled" = false
	"Molding Lands Enabled" = false
	"Nurturing Roots Enabled" = false
	"Advantageous Growth Enabled" = false
	"Forest Affinity Enabled" = false
	"Mind Bender Enabled" = false
	"Ghostly Steed Enabled" = false
	"Withering Stench Enabled" = false
	"Dark Age Enabled" = false
	"Rotten Heart Enabled" = false
	"Nocturnal Enabled" = false
	"Coven's Rule Enabled" = false

["Costs and Cooldowns: (Cooldowns are in ticks)"]
	#DEFAULT = 8
	"Self Propulsion Cost" = 8
	#DEFAULT = 50
	"Self Propulsion Cooldown" = 50
	#DEFAULT = 10
	"Force of Wind Cost" = 10
	#DEFAULT = 70
	"Force of Wind Cooldown" = 70
	#DEFAULT = 40
	"Strike From Above Cost" = 40
	#DEFAULT = 200
	"Strike From Above Cooldown" = 200
	#DEFAULT = 70
	"Everchanging Skies Cost" = 70
	#DEFAULT = 600
	"Everchanging Skies Cooldown" = 600
	#DEFAULT = 25
	"Lifebringer Cost" = 25
	#DEFAULT = 80
	"Lifebringer Cooldown" = 80
	#DEFAULT = 60
	"Beast Tamer Cost" = 60
	#DEFAULT = 60
	"Beast Tamer Cooldown" = 60
	#DEFAULT = 20
	"Wild Aid Cost" = 20
	#DEFAULT = 80
	"Wild Aid Cooldown" = 80
	#DEFAULT = 55
	"Molding Lands Cost" = 55
	#DEFAULT = 35
	"Molding Lands Cooldown" = 35
	#DEFAULT = 30
	"Mind Bender Cost" = 30
	#DEFAULT = 50
	"Mind Bender Cooldown" = 50
	#DEFAULT = 35
	"Ghostly Steed Cost" = 35
	#DEFAULT = 200
	"Ghostly Steed Cooldown" = 200
	#DEFAULT = 20
	"Withering Stench Cost" = 20
	#DEFAULT = 35
	"Withering Stench Cooldown" = 35
	#DEFAULT = 70
	"Dark Age Cost" = 70
	#DEFAULT = 4000
	"Dark Age Cooldown" = 4000

